config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts

  get 'about' => 'welcome/about'

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :body))
    if @post.save
      flash[:notice] = "I feel good"
      redirect_to @post
    else
      flash[:notice] = "I feel bad"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params.require(:post).permit(:title, :body))
      flash[:notice] = "I feel better now"
      redirect_to @post
    else
      flash[:notice] = "I could feel better, but i don't"
      render :edit
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ketokitten</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <ul class="nav nav-tabs">
    <li><%=link_to 'Home', root_path %></li>
    <li><%=link_to 'About', about_path %></li>
  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
<%= yield %>

</div>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>

<div class='row'>
  <div class='col-md-4'>
    <p>Guidelines for posts</p>
    <ul>
      <li>First</li>
      <li>Second</li>
      <li>Third</li>
    </ul>
  </div>

	<div class='col-md-4'>
	  <%= form_for @post do |f| %>
		  <div class='form-group'>
		    <%= f.label :title %>
		    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter a title' %>
		  </div>

		  <div class='form-group'>
		    <%= f.label :body %>
		    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter a description" %>
		  </div>

		  <div class='form-group'>
		    <%= f.submit 'Save', class: 'btn btn-success' %>
		  </div>
	  <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
  <div class=media>
    <div class="media-body">
    <h4 class=media-heading>
      <%= link_to post.title, post %>
    </h4>
  </div>
 </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class='row'>
  <div class='col-md-4'>
    <p>Guidelines for posts</p>
    <ul>
      <li>First</li>
      <li>Second</li>
      <li>Third</li>
    </ul>
  </div>

	<div class='col-md-4'>
	  <%= form_for @post do |f| %>
		  <div class='form-group'>
		    <%= f.label :title %>
		    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter a title' %>
		  </div>

		  <div class='form-group'>
		    <%= f.label :body %>
		    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter a description" %>
		  </div>

		  <div class='form-group'>
		    <%= f.submit 'Save', class: 'btn btn-success' %>
		  </div>
	  <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %> </h1>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-success' %>

<p><%= @post.body %> </p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Keto Kitten</h1>
<p id="index-title">Home page of the Keto Kitten</p>

<div class="posts">Post 1</div>
<div class="posts">Post 2</div>

<section>This is the content in a section element. </section>